site_name: VenafiTppPS
repo_url: https://github.com/gdbarron/VenafiTppPS
site_author: Greg Brownstein
edit_uri: edit/master/docs/
theme: readthedocs
copyright: ""
pages:
  - Home: index.md
  - Release Notes: RELEASE.md
  - Change Log: ChangeLog.md
  - Functions:
    - Get-TppAttribute: functions/Get-TppAttribute.md
    - Get-TppCertificateDetail: functions/Get-TppCertificateDetail.md
    - Get-TppCustomField: functions/Get-TppCustomField.md
    - Get-TppIdentity: functions/Get-TppIdentity.md
    - Get-TppIdentityAttribute: functions/Get-TppIdentityAttribute.md
    - Get-TppLog: functions/Get-TppLog.md
    - Get-TppObject: functions/Get-TppObject.md
    - Get-TppPermission: functions/Get-TppPermission.md
    - Get-TppWorkflowDetail: functions/Get-TppWorkflowDetail.md
    - Move-TppObject: functions/Move-TppObject.md
    - New-TppCapiApplication: functions/New-TppCapiApplication.md
    - New-TppCertificate: functions/New-TppCertificate.md
    - New-TppPolicy: functions/New-TppPolicy.md
    - New-TppSession: functions/New-TppSession.md
    - Remove-TppCertificateAssociation: functions/Remove-TppCertificateAssociation.md
    - Rename-TppObject: functions/Rename-TppObject.md
    - Restore-TppCertificate: functions/Restore-TppCertificate.md
    - Revoke-TppCertificate: functions/Revoke-TppCertificate.md
    - Set-TppAttribute: functions/Set-TppAttribute.md
    - Set-TppPermission: functions/Set-TppPermission.md
    - Set-TppWorkflowStatus: functions/Set-TppWorkflowStatus.md
    - Test-TppIdentity: functions/Test-TppIdentity.md
    - Test-TppObject: functions/Test-TppObject.md

