site_name: VenafiTppPS
repo_url: https://github.com/gdbarron/VenafiTppPS
site_author: Greg Brownstein
edit_uri: edit/master/docs/
theme: readthedocs
copyright: ""
pages:
  - Home: index.md
  - Functions:
    - Get-TppAttribute: functions/Get-TppAttribute.md
    - Get-TppCertificateDetail: functions/Get-TppCertificateDetail.md
    - Get-TppCustomField: functions/Get-TppCustomField.md
    - Get-TppObject: functions/Get-TppObject.md
    - Get-TppWorkflowDetail: functions/Get-TppWorkflowDetail.md
    - Invoke-TppCertificateRenewal: functions/Invoke-TppCertificateRenewal.md
    - Move-TppObject: functions/Move-TppObject.md
    - New-TppCapiApplication: functions/New-TppCapiApplication.md
    - New-TppSession: functions/New-TppSession.md
    - Rename-TppObject: functions/Rename-TppObject.md
    - Set-TppAttribute: functions/Set-TppAttribute.md
    - Test-TppObjectExists: functions/Test-TppObjectExists.md

